@startuml Диаграмма состаяний проекта


[*] --> Новый
Новый --> Согласован
Новый --> Отменен

Согласован --> Отменен
Согласован --> InProgress

state "В работе" as InProgress
InProgress --> Отменен
InProgress --> Приостановлен
InProgress --> Завершен

Приостановлен --> InProgress
Приостановлен --> Отменен

Отменен --> [*]
Завершен --> [*]

@enduml